#!/bin/bash

## delete all log files and journal files
rm -rf -v *.log *.jou *.str

## delete all directories generated by Vivado FPGA implementation flows 
rm -rf -v *.cache
rm -rf -v *.hw
rm -rf -v *.ip_user_files
rm -rf -v *.runs
rm -rf -v *.sim
rm -rf -v .Xil
