#!/bin/bash

## delete all log files, journal files and project files
rm -rf -v *.log *.jou *.str *.xpr *.bit *.bin

## delete all project directories generated by Vivado FPGA implementation flows 
rm -rf -v *.cache
rm -rf -v *.hw
rm -rf -v *.ip_user_files
rm -rf -v *.runs
rm -rf -v *.sim
rm -rf -v *.srcs
rm -rf -v .Xil
