::
:: **NOTE
::
:: This is a Windows batch script (.bat) but we are assuming to use
:: the 'rm.exe' executable that comes with the GNU Win package as
:: under Linux! If you want to use native Windows commands you must
:: invoke 'del' for files and 'rmdir' for directories instead.
::

:: turn-off command echoing
@echo off

:: delete all log files, journal files and project files (use rm.exe from GNU Win)
rm -rf -v *.log *.jou *.str *.xpr *.xml *.bit *.bin

:: delete all project directories generated by Vivado FPGA implementation flows 
rm -rf -v *.cache
rm -rf -v *.hbs
rm -rf -v *.hw
rm -rf -v *.ip_user_files
rm -rf -v *.runs
rm -rf -v *.sim
rm -rf -v *.srcs
rm -rf -v .Xil
